# Generated by Django 2.0.7 on 2018-07-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuites', '0002_auto_20180730_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuite',
            name='content',
            field=models.CharField(max_length=280, verbose_name='Tuite'),
        ),
    ]
