# Generated by Django 2.0.8 on 2018-08-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuites', '0005_auto_20180731_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuite',
            options={'ordering': ('date_created',)},
        ),
    ]
